name: Update Script Version

on:
  push:
  pull_request:

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Check if main.py has been modified since the last commit
      - name: Check for modifications to main.py
        run: |
          if ! git diff-tree --no-commit-id --name-only -r HEAD | grep -q "main.py"; then
            echo "No changes to main.py since last commit"
            exit 0
          fi

      # Check if the SCRIPT_VERSION has been manually updated before being pushed
      - name: Check if SCRIPT_VERSION has been manually updated
        run: |
          # Get the current SCRIPT_VERSION from main.py
          SCRIPT_VERSION=$(grep "SCRIPT_VERSION = " main.py | cut -d "=" -f 2 | tr -d " '\"")

          # Check if the SCRIPT_VERSION has been manually updated
          if [[ "$SCRIPT_VERSION" =~ ^[0-9]+.[0-9]+$ ]]; then
            echo "SCRIPT_VERSION has been manually updated"
            exit 0
          fi

      # Update the SCRIPT_VERSION in main.py
      - name: Update SCRIPT_VERSION
        run: |
          # Get the current SCRIPT_VERSION from main.py
          SCRIPT_VERSION=$(grep "SCRIPT_VERSION = " main.py | cut -d "=" -f 2 | tr -d " '\"")

          # Increment the SCRIPT_VERSION by 0.1
          NEW_SCRIPT_VERSION=$(awk -v x=$SCRIPT_VERSION 'BEGIN { printf "%.1f", x+0.1 }')

          # Update the SCRIPT_VERSION in main.py
          sed -i "s/$SCRIPT_VERSION/$NEW_SCRIPT_VERSION/g" main.py
          echo "### THE SCRIPT UPDATED ###"